// TODO - ADD getstaticprops ?

// TODO - Add a 'Principles' section, which lists my coding principles/philosophies, e.g: Responsive, mobile-first design built to work no matter the device or browser, clean code written to be easily understandable, maintainable, scalable and reusable etc?

import { Fragment, useRef } from 'react';
import Head from 'next/head';

import About from '../components/homepage-sections/about/About';
import Introduction from '../components/homepage-sections/introduction/Introduction';
import Projects from '../components/homepage-sections/projects/Projects';
import Tools from '../components/homepage-sections/tools/Tools';
import Contact from '../components/homepage-sections/contact/Contact';

export const aboutSection = 'about';
export let aboutSectionRef;
export const contactSection = 'contact';
export let contactSectionRef;
export const introductionSection = 'introduction';
export let introductionSectionRef;
export const projectsSection = 'projects';
export let projectsSectionsRef;
export const toolsSection = 'tools';
export let toolsSectionRef;

export const sectionOrder = [
  introductionSection,
  aboutSection,
  toolsSection,
  projectsSection,
  contactSection,
];
export const darkSections = [introductionSection, toolsSection, projectsSection, contactSection];

export const aboutTitle = 'about-title';
export let aboutTitleRef;
export const aboutSkills = 'about-skills';
export let aboutSkillsRef;
const aboutElements = [aboutTitle, aboutSkills];

export const contactTitle = 'contact-title';
export let contactTitleRef;
export const contactForm = 'contact-form';
export let contactFormRef;
export const contactJethroCodesLink = 'contact-jethro-codes-link';
export let contactJethroCodesLinkRef;
export const contactSocialMediaLinks = 'contact-social-media-links';
export let contactSocialMediaLinksRef;
const contactElements = [
  contactTitle,
  contactForm,
  contactJethroCodesLink,
  contactSocialMediaLinks,
];

export const introductionTitle = 'introduction-title';
export let introductionTitleRef;
export const introductionDescription = 'introduction-description';
export let introductionDescriptionRef;
export const introductionFindOutMoreMobileLink = 'introduction-find-out-more-mobile-link';
export let introductionFindOutMoreMobileLinkRef;
export const introductionFindOutMoreDesktopLink = 'introduction-find-out-more-desktop-link';
export let introductionFindOutMoreDesktopLinkRef;
export const introductionPortrait = 'introduction-portrait';
export let introductionPortraitRef;
const introductionElements = [
  introductionTitle,
  introductionDescription,
  introductionFindOutMoreMobileLink,
  introductionFindOutMoreDesktopLink,
  introductionPortrait,
];

export const projectsTitle = 'projects-title';
export let projectsTitleRef;
export const projectsCards = 'projects-cards';
export let projectsCardsRef;
const projectsElements = [projectsTitle, projectsCards];

export const toolsTitle = 'tools-title';
export let toolsTitleRef;
export const toolsDescription = 'tools-description';
export let toolsDescriptionRef;
export const toolsIcons = 'tools-icons';
export let toolsIconsRef;
const toolsElements = [toolsTitle, toolsDescription, toolsIcons];

export const refElementNames = [
  ...sectionOrder,
  ...aboutElements,
  ...contactElements,
  ...introductionElements,
  ...projectsElements,
  ...toolsElements,
];

const HomePage = () => {
  aboutSectionRef = useRef();
  contactSectionRef = useRef();
  introductionSectionRef = useRef();
  projectsSectionsRef = useRef();
  toolsSectionRef = useRef();

  aboutTitleRef = useRef();
  aboutSkillsRef = useRef();

  contactTitleRef = useRef();
  contactFormRef = useRef();
  contactJethroCodesLinkRef = useRef();
  contactSocialMediaLinksRef = useRef();

  introductionTitleRef = useRef();
  introductionDescriptionRef = useRef();
  introductionFindOutMoreMobileLinkRef = useRef();
  introductionFindOutMoreDesktopLinkRef = useRef();
  introductionPortraitRef = useRef();

  projectsTitleRef = useRef();
  projectsCardsRef = useRef();

  toolsTitleRef = useRef();
  toolsDescriptionRef = useRef();
  toolsIconsRef = useRef();

  const component = componentName => {
    const key = `${componentName}-component`;

    switch (componentName) {
      case aboutSection:
        return <About key={key} />;
      case contactSection:
        return <Contact key={key} />;
      case introductionSection:
        return <Introduction key={key} />;
      case projectsSection:
        return <Projects key={key} />;
      case toolsSection:
        return <Tools key={key} />;
      default:
        throw new Error('Unknown componentName in component function of HomePage');
    }
  };

  return (
    <Fragment>
      <Head>
        {/* TODO - Update this */}
        <title>Jethro Williams - Software Engineer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      {sectionOrder.map(section => component(section))}
    </Fragment>
  );
};

export default HomePage;
