import { Fragment } from 'react';
import Head from 'next/head';

const HomePage = () => {
  return (
    <Fragment>
      <Head>
        {/* TODO - Update this */}
        <title>Jethro Williams - Software Engineer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div>I'm the homepage</div>
    </Fragment>
  );
};

export default HomePage;
