import { Fragment } from 'react';
import Head from 'next/head';

import Introduction from '../components/homepage-sections/introduction/Introduction';
import Tools from '../components/homepage-sections/tools/Tools';
import Projects from '../components/homepage-sections/projects/Projects';

const IntroductionSecion = 'introduction';
const ToolsSection = 'tools';
const ProjectsSection = 'projects';

export const sectionOrder = [IntroductionSecion, ToolsSection, ProjectsSection];

const HomePage = () => {
  const component = componentName => {
    switch (componentName) {
      case IntroductionSecion:
        return <Introduction key={componentName} />;
      case ToolsSection:
        return <Tools key={componentName} />;
      case ProjectsSection:
        return <Projects key={componentName} />;
      default:
        throw new Error('Unknown componentName in component() function of HomePage');
    }
  };

  return (
    <Fragment>
      <Head>
        {/* TODO - Update this */}
        <title>Jethro Williams - Software Engineer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      {sectionOrder.map(section => component(section))}
    </Fragment>
  );
};

export default HomePage;
